# Generated by Django 3.1.6 on 2021-04-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
    ]
